CREATE TABLE CRICKET(
AGE INT,
NAME VARCHAR(50),
CITY VARCHAR(50)
);

CREATE TABLE EMPLOYEE(
NAME VARCHAR(50),
CITY VARCHAR(50),
AGE INT
);

INSERT INTO CRICKET VALUES(30,'SACHIN TENDULKER','MUMBAI')
INSERT INTO CRICKET VALUES(35,'RAHUL DRAVID','BOMBAY')
INSERT INTO CRICKET VALUES(31,'M.S.DHONI','JHARKHAND')
INSERT INTO CRICKET VALUES(30,'SURESH RAINA','GUJARAT')
SELECT *FROM CRICKET

INSERT INTO EMPLOYEE VALUES('JAY PATEL','RAJKOT',30)
INSERT INTO EMPLOYEE VALUES('RAHUL DAVE','BARODA',35)
INSERT INTO EMPLOYEE VALUES('JEET PATET','SURAT',31)
INSERT INTO EMPLOYEE VALUES('VIJAY RAVAL','RAJKOT',30)
SELECT *FROM EMPLOYEE

SELECT *INTO WORLDCUP FROM CRICKET
SELECT *FROM WORLDCUP

SELECT AGE,NAME INTO T20 FROM CRICKET
SELECT *FROM T20

SELECT AGE,NAME INTO T20_BACKUP FROM CRICKET WHERE 1=0
SELECT *FROM T20_BACKUP

SELECT *INTO IPL FROM CRICKET WHERE 1=0
SELECT *FROM IPL

SELECT *INTO EMPLOYEE_DETAIL FROM EMPLOYEE
SELECT *FROM EMPLOYEE_DETAIL

SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE WHERE 1=0
SELECT *FROM EMPLOYEE_DATA


SELECT *INTO EMPLOYEE_INFO FROM EMPLOYEE WHERE 1=0
SELECT *FROM EMPLOYEE_INFO

INSERT INTO EMPLOYEE_INFO
SELECT *FROM EMPLOYEE WHERE CITY='RAJKOT'
SELECT *FROM EMPLOYEE_INFO

INSERT INTO EMPLOYEE_INFO
SELECT *FROM EMPLOYEE WHERE AGE>32
SELECT *FROM EMPLOYEE_INFO

--UPDATE----------------------

UPDATE DEPOSIT SET AMOUNT=5000 WHERE AMOUNT=3000
SELECT *FROM DEPOSIT

UPDATE BORROW SET BNAME='C.G.ROAD' WHERE CNAME='ANIL'
SELECT *FROM BORROW

UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000 WHERE CNAME='SANDIP'

UPDATE DEPOSIT SET AMOUNT=7000 WHERE CNAME='KRANTI' 

UPDATE BRANCH SET BNAME='ANDHERI WEST' WHERE BNAME='ANDHERI'

UPDATE DEPOSIT SET BNAME='NEHRU PLACE' WHERE CNAME='MEHUL'

UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO BETWEEN 103 AND 107

UPDATE DEPOSIT SET ADATE='1995-4-1' WHERE CNAME='ANIT'

UPDATE DEPOSIT SET AMOUNT=1000 WHERE CNAME='MINU'

UPDATE DEPOSIT SET AMOUNT=5000,ADATE='1996-4-1' WHERE CNAME='PRAMOD' 

UPDATE BORROW SET AMOUNT=AMOUNT*0.1+AMOUNT

UPDATE DEPOSIT SET AMOUNT=AMOUNT*0.1+AMOUNT

UPDATE BORROW SET LOANNO=NULL WHERE LOANNO=321

UPDATE BORROW SET BNAME=NULL WHERE CNAME='KRANTI'

SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

SELECT BNAME FROM BORROW WHERE BNAME IS NOT NULL

UPDATE BORROW SET LOANNO=5000,BNAME='VRCE',CNAME='DARSHAN' WHERE LOANNO=481

UPDATE DEPOSIT SET ADATE='2021-02-01' WHERE AMOUNT<2000

UPDATE DEPOSIT SET ADATE=NULL,BNAME='ANDHERI' WHERE ACTNO=110









